// Code generated by genji.
// DO NOT EDIT!

package model

import (
	"errors"

	"github.com/asdine/genji/field"
	"github.com/asdine/genji/index"
	"github.com/asdine/genji/query"
	"github.com/asdine/genji/record"
)

// GetField implements the field method of the record.Record interface.
func (d *Domain) GetField(name string) (field.Field, error) {
	switch name {
	case "Id":
		return field.NewString("Id", d.Id), nil
	case "ServiceInstanceId":
		return field.NewString("ServiceInstanceId", d.ServiceInstanceId), nil
	case "Name":
		return field.NewString("Name", d.Name), nil
	}

	return field.Field{}, errors.New("unknown field")
}

// Iterate through all the fields one by one and pass each of them to the given function.
// It the given function returns an error, the iteration is interrupted.
func (d *Domain) Iterate(fn func(field.Field) error) error {
	var err error

	err = fn(field.NewString("Id", d.Id))
	if err != nil {
		return err
	}

	err = fn(field.NewString("ServiceInstanceId", d.ServiceInstanceId))
	if err != nil {
		return err
	}

	err = fn(field.NewString("Name", d.Name))
	if err != nil {
		return err
	}

	return nil
}

// ScanRecord extracts fields from record and assigns them to the struct fields.
// It implements the record.Scanner interface.
func (d *Domain) ScanRecord(rec record.Record) error {
	return rec.Iterate(func(f field.Field) error {
		var err error

		switch f.Name {
		case "Id":
			d.Id, err = field.DecodeString(f.Data)
		case "ServiceInstanceId":
			d.ServiceInstanceId, err = field.DecodeString(f.Data)
		case "Name":
			d.Name, err = field.DecodeString(f.Data)
		}
		return err
	})
}

// PrimaryKey returns the primary key. It implements the table.PrimaryKeyer interface.
func (d *Domain) PrimaryKey() ([]byte, error) {
	return field.EncodeString(d.Id), nil
}

// Indexes creates a map containing the configuration for each index of the table.
func (d *Domain) Indexes() map[string]index.Options {
	return map[string]index.Options{
		"Name": index.Options{Unique: true},
	}
}

// DomainFields describes the fields of the Domain record.
// It can be used to select fields during queries.
type DomainFields struct {
	Id                query.StringFieldSelector
	ServiceInstanceId query.StringFieldSelector
	Name              query.StringFieldSelector
}

// NewDomainFields creates a DomainFields.
func NewDomainFields() *DomainFields {
	return &DomainFields{
		Id:                query.StringField("Id"),
		ServiceInstanceId: query.StringField("ServiceInstanceId"),
		Name:              query.StringField("Name"),
	}
}
