// Code generated by genji.
// DO NOT EDIT!

package model

import (
	"errors"

	"github.com/asdine/genji/field"
	"github.com/asdine/genji/index"
	"github.com/asdine/genji/query"
	"github.com/asdine/genji/record"
)

// GetField implements the field method of the record.Record interface.
func (m *MailboxMessage) GetField(name string) (field.Field, error) {
	switch name {
	case "MailboxId":
		return field.NewString("MailboxId", m.MailboxId), nil
	case "MessageId":
		return field.NewString("MessageId", m.MessageId), nil
	case "Uid":
		return field.NewUint32("Uid", m.Uid), nil
	case "FlagsCSV":
		return field.NewString("FlagsCSV", m.FlagsCSV), nil
	}

	return field.Field{}, errors.New("unknown field")
}

// Iterate through all the fields one by one and pass each of them to the given function.
// It the given function returns an error, the iteration is interrupted.
func (m *MailboxMessage) Iterate(fn func(field.Field) error) error {
	var err error

	err = fn(field.NewString("MailboxId", m.MailboxId))
	if err != nil {
		return err
	}

	err = fn(field.NewString("MessageId", m.MessageId))
	if err != nil {
		return err
	}

	err = fn(field.NewUint32("Uid", m.Uid))
	if err != nil {
		return err
	}

	err = fn(field.NewString("FlagsCSV", m.FlagsCSV))
	if err != nil {
		return err
	}

	return nil
}

// ScanRecord extracts fields from record and assigns them to the struct fields.
// It implements the record.Scanner interface.
func (m *MailboxMessage) ScanRecord(rec record.Record) error {
	return rec.Iterate(func(f field.Field) error {
		var err error

		switch f.Name {
		case "MailboxId":
			m.MailboxId, err = field.DecodeString(f.Data)
		case "MessageId":
			m.MessageId, err = field.DecodeString(f.Data)
		case "Uid":
			m.Uid, err = field.DecodeUint32(f.Data)
		case "FlagsCSV":
			m.FlagsCSV, err = field.DecodeString(f.Data)
		}
		return err
	})
}

// Indexes creates a map containing the configuration for each index of the table.
func (m *MailboxMessage) Indexes() map[string]index.Options {
	return map[string]index.Options{
		"MailboxId": index.Options{Unique: false},
		"MessageId": index.Options{Unique: false},
		"Uid":       index.Options{Unique: false},
	}
}

// MailboxMessageFields describes the fields of the MailboxMessage record.
// It can be used to select fields during queries.
type MailboxMessageFields struct {
	MailboxId query.StringFieldSelector
	MessageId query.StringFieldSelector
	Uid       query.Uint32FieldSelector
	FlagsCSV  query.StringFieldSelector
}

// NewMailboxMessageFields creates a MailboxMessageFields.
func NewMailboxMessageFields() *MailboxMessageFields {
	return &MailboxMessageFields{
		MailboxId: query.StringField("MailboxId"),
		MessageId: query.StringField("MessageId"),
		Uid:       query.Uint32Field("Uid"),
		FlagsCSV:  query.StringField("FlagsCSV"),
	}
}
