// Code generated by genji.
// DO NOT EDIT!

package model

import (
	"errors"

	"github.com/asdine/genji/field"
	"github.com/asdine/genji/index"
	"github.com/asdine/genji/query"
	"github.com/asdine/genji/record"
)

// GetField implements the field method of the record.Record interface.
func (m *Message) GetField(name string) (field.Field, error) {
	switch name {
	case "ID":
		return field.NewString("ID", m.ID), nil
	case "DateUTC":
		return field.NewInt64("DateUTC", m.DateUTC), nil
	case "Size":
		return field.NewUint32("Size", m.Size), nil
	}

	return field.Field{}, errors.New("unknown field")
}

// Iterate through all the fields one by one and pass each of them to the given function.
// It the given function returns an error, the iteration is interrupted.
func (m *Message) Iterate(fn func(field.Field) error) error {
	var err error

	err = fn(field.NewString("ID", m.ID))
	if err != nil {
		return err
	}

	err = fn(field.NewInt64("DateUTC", m.DateUTC))
	if err != nil {
		return err
	}

	err = fn(field.NewUint32("Size", m.Size))
	if err != nil {
		return err
	}

	return nil
}

// ScanRecord extracts fields from record and assigns them to the struct fields.
// It implements the record.Scanner interface.
func (m *Message) ScanRecord(rec record.Record) error {
	return rec.Iterate(func(f field.Field) error {
		var err error

		switch f.Name {
		case "ID":
			m.ID, err = field.DecodeString(f.Data)
		case "DateUTC":
			m.DateUTC, err = field.DecodeInt64(f.Data)
		case "Size":
			m.Size, err = field.DecodeUint32(f.Data)
		}
		return err
	})
}

// PrimaryKey returns the primary key. It implements the table.PrimaryKeyer interface.
func (m *Message) PrimaryKey() ([]byte, error) {
	return field.EncodeString(m.ID), nil
}

// Indexes creates a map containing the configuration for each index of the table.
func (m *Message) Indexes() map[string]index.Options {
	return map[string]index.Options{
		"DateUTC": index.Options{Unique: false},
	}
}

// MessageFields describes the fields of the Message record.
// It can be used to select fields during queries.
type MessageFields struct {
	ID      query.StringFieldSelector
	DateUTC query.Int64FieldSelector
	Size    query.Uint32FieldSelector
}

// NewMessageFields creates a MessageFields.
func NewMessageFields() *MessageFields {
	return &MessageFields{
		ID:      query.StringField("ID"),
		DateUTC: query.Int64Field("DateUTC"),
		Size:    query.Uint32Field("Size"),
	}
}
