// Code generated by genji.
// DO NOT EDIT!

package model

import (
	"errors"

	"github.com/asdine/genji/field"
	"github.com/asdine/genji/query"
	"github.com/asdine/genji/record"
)

// GetField implements the field method of the record.Record interface.
func (m *MessageRawBody) GetField(name string) (field.Field, error) {
	switch name {
	case "Id":
		return field.NewString("Id", m.Id), nil
	case "Body":
		return field.NewBytes("Body", m.Body), nil
	}

	return field.Field{}, errors.New("unknown field")
}

// Iterate through all the fields one by one and pass each of them to the given function.
// It the given function returns an error, the iteration is interrupted.
func (m *MessageRawBody) Iterate(fn func(field.Field) error) error {
	var err error

	err = fn(field.NewString("Id", m.Id))
	if err != nil {
		return err
	}

	err = fn(field.NewBytes("Body", m.Body))
	if err != nil {
		return err
	}

	return nil
}

// ScanRecord extracts fields from record and assigns them to the struct fields.
// It implements the record.Scanner interface.
func (m *MessageRawBody) ScanRecord(rec record.Record) error {
	return rec.Iterate(func(f field.Field) error {
		var err error

		switch f.Name {
		case "Id":
			m.Id, err = field.DecodeString(f.Data)
		case "Body":
			m.Body, err = field.DecodeBytes(f.Data)
		}
		return err
	})
}

// PrimaryKey returns the primary key. It implements the table.PrimaryKeyer interface.
func (m *MessageRawBody) PrimaryKey() ([]byte, error) {
	return field.EncodeString(m.Id), nil
}

// MessageRawBodyFields describes the fields of the MessageRawBody record.
// It can be used to select fields during queries.
type MessageRawBodyFields struct {
	Id   query.StringFieldSelector
	Body query.BytesFieldSelector
}

// NewMessageRawBodyFields creates a MessageRawBodyFields.
func NewMessageRawBodyFields() *MessageRawBodyFields {
	return &MessageRawBodyFields{
		Id:   query.StringField("Id"),
		Body: query.BytesField("Body"),
	}
}
