// Code generated by genji.
// DO NOT EDIT!

package model

import (
	"errors"

	"github.com/asdine/genji/field"
	"github.com/asdine/genji/index"
	"github.com/asdine/genji/query"
	"github.com/asdine/genji/record"
)

// GetField implements the field method of the record.Record interface.
func (p *Property) GetField(name string) (field.Field, error) {
	switch name {
	case "ID":
		return field.NewString("ID", p.ID), nil
	case "Name":
		return field.NewString("Name", p.Name), nil
	case "Value":
		return field.NewString("Value", p.Value), nil
	}

	return field.Field{}, errors.New("unknown field")
}

// Iterate through all the fields one by one and pass each of them to the given function.
// It the given function returns an error, the iteration is interrupted.
func (p *Property) Iterate(fn func(field.Field) error) error {
	var err error

	err = fn(field.NewString("ID", p.ID))
	if err != nil {
		return err
	}

	err = fn(field.NewString("Name", p.Name))
	if err != nil {
		return err
	}

	err = fn(field.NewString("Value", p.Value))
	if err != nil {
		return err
	}

	return nil
}

// ScanRecord extracts fields from record and assigns them to the struct fields.
// It implements the record.Scanner interface.
func (p *Property) ScanRecord(rec record.Record) error {
	return rec.Iterate(func(f field.Field) error {
		var err error

		switch f.Name {
		case "ID":
			p.ID, err = field.DecodeString(f.Data)
		case "Name":
			p.Name, err = field.DecodeString(f.Data)
		case "Value":
			p.Value, err = field.DecodeString(f.Data)
		}
		return err
	})
}

// PrimaryKey returns the primary key. It implements the table.PrimaryKeyer interface.
func (p *Property) PrimaryKey() ([]byte, error) {
	return field.EncodeString(p.ID), nil
}

// Indexes creates a map containing the configuration for each index of the table.
func (p *Property) Indexes() map[string]index.Options {
	return map[string]index.Options{
		"Name": index.Options{Unique: true},
	}
}

// PropertyFields describes the fields of the Property record.
// It can be used to select fields during queries.
type PropertyFields struct {
	ID    query.StringFieldSelector
	Name  query.StringFieldSelector
	Value query.StringFieldSelector
}

// NewPropertyFields creates a PropertyFields.
func NewPropertyFields() *PropertyFields {
	return &PropertyFields{
		ID:    query.StringField("ID"),
		Name:  query.StringField("Name"),
		Value: query.StringField("Value"),
	}
}
