// Code generated by genji.
// DO NOT EDIT!

package model

import (
	"errors"

	"github.com/asdine/genji/field"
	"github.com/asdine/genji/query"
	"github.com/asdine/genji/record"
)

// GetField implements the field method of the record.Record interface.
func (s *Snapshot) GetField(name string) (field.Field, error) {
	switch name {
	case "Id":
		return field.NewString("Id", s.Id), nil
	case "Name":
		return field.NewString("Name", s.Name), nil
	}

	return field.Field{}, errors.New("unknown field")
}

// Iterate through all the fields one by one and pass each of them to the given function.
// It the given function returns an error, the iteration is interrupted.
func (s *Snapshot) Iterate(fn func(field.Field) error) error {
	var err error

	err = fn(field.NewString("Id", s.Id))
	if err != nil {
		return err
	}

	err = fn(field.NewString("Name", s.Name))
	if err != nil {
		return err
	}

	return nil
}

// ScanRecord extracts fields from record and assigns them to the struct fields.
// It implements the record.Scanner interface.
func (s *Snapshot) ScanRecord(rec record.Record) error {
	return rec.Iterate(func(f field.Field) error {
		var err error

		switch f.Name {
		case "Id":
			s.Id, err = field.DecodeString(f.Data)
		case "Name":
			s.Name, err = field.DecodeString(f.Data)
		}
		return err
	})
}

// PrimaryKey returns the primary key. It implements the table.PrimaryKeyer interface.
func (s *Snapshot) PrimaryKey() ([]byte, error) {
	return field.EncodeString(s.Id), nil
}

// SnapshotFields describes the fields of the Snapshot record.
// It can be used to select fields during queries.
type SnapshotFields struct {
	Id   query.StringFieldSelector
	Name query.StringFieldSelector
}

// NewSnapshotFields creates a SnapshotFields.
func NewSnapshotFields() *SnapshotFields {
	return &SnapshotFields{
		Id:   query.StringField("Id"),
		Name: query.StringField("Name"),
	}
}
