// Code generated by protoc-gen-go. DO NOT EDIT.
// source: email.proto

package emailproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClientMessage struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to MessageType:
	//	*ClientMessage_AckResponse
	//	*ClientMessage_NoopRequest
	//	*ClientMessage_StartupRequest
	//	*ClientMessage_ErrorResponse
	MessageType          isClientMessage_MessageType `protobuf_oneof:"message_type"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ClientMessage) Reset()         { *m = ClientMessage{} }
func (m *ClientMessage) String() string { return proto.CompactTextString(m) }
func (*ClientMessage) ProtoMessage()    {}
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{0}
}

func (m *ClientMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientMessage.Unmarshal(m, b)
}
func (m *ClientMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientMessage.Marshal(b, m, deterministic)
}
func (m *ClientMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientMessage.Merge(m, src)
}
func (m *ClientMessage) XXX_Size() int {
	return xxx_messageInfo_ClientMessage.Size(m)
}
func (m *ClientMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ClientMessage proto.InternalMessageInfo

func (m *ClientMessage) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type isClientMessage_MessageType interface {
	isClientMessage_MessageType()
}

type ClientMessage_AckResponse struct {
	AckResponse *AckResponse `protobuf:"bytes,2,opt,name=ack_response,json=ackResponse,proto3,oneof"`
}

type ClientMessage_NoopRequest struct {
	NoopRequest *NoopRequest `protobuf:"bytes,3,opt,name=noop_request,json=noopRequest,proto3,oneof"`
}

type ClientMessage_StartupRequest struct {
	StartupRequest *StartupRequest `protobuf:"bytes,4,opt,name=startup_request,json=startupRequest,proto3,oneof"`
}

type ClientMessage_ErrorResponse struct {
	ErrorResponse *ErrorResponse `protobuf:"bytes,5,opt,name=error_response,json=errorResponse,proto3,oneof"`
}

func (*ClientMessage_AckResponse) isClientMessage_MessageType() {}

func (*ClientMessage_NoopRequest) isClientMessage_MessageType() {}

func (*ClientMessage_StartupRequest) isClientMessage_MessageType() {}

func (*ClientMessage_ErrorResponse) isClientMessage_MessageType() {}

func (m *ClientMessage) GetMessageType() isClientMessage_MessageType {
	if m != nil {
		return m.MessageType
	}
	return nil
}

func (m *ClientMessage) GetAckResponse() *AckResponse {
	if x, ok := m.GetMessageType().(*ClientMessage_AckResponse); ok {
		return x.AckResponse
	}
	return nil
}

func (m *ClientMessage) GetNoopRequest() *NoopRequest {
	if x, ok := m.GetMessageType().(*ClientMessage_NoopRequest); ok {
		return x.NoopRequest
	}
	return nil
}

func (m *ClientMessage) GetStartupRequest() *StartupRequest {
	if x, ok := m.GetMessageType().(*ClientMessage_StartupRequest); ok {
		return x.StartupRequest
	}
	return nil
}

func (m *ClientMessage) GetErrorResponse() *ErrorResponse {
	if x, ok := m.GetMessageType().(*ClientMessage_ErrorResponse); ok {
		return x.ErrorResponse
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ClientMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ClientMessage_AckResponse)(nil),
		(*ClientMessage_NoopRequest)(nil),
		(*ClientMessage_StartupRequest)(nil),
		(*ClientMessage_ErrorResponse)(nil),
	}
}

type ServerMessage struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to MessageType:
	//	*ServerMessage_AckResponse
	//	*ServerMessage_NoopRequest
	//	*ServerMessage_ErrorResponse
	//	*ServerMessage_ClaimRequest
	//	*ServerMessage_ConfigChangedRequest
	MessageType          isServerMessage_MessageType `protobuf_oneof:"message_type"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ServerMessage) Reset()         { *m = ServerMessage{} }
func (m *ServerMessage) String() string { return proto.CompactTextString(m) }
func (*ServerMessage) ProtoMessage()    {}
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{1}
}

func (m *ServerMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerMessage.Unmarshal(m, b)
}
func (m *ServerMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerMessage.Marshal(b, m, deterministic)
}
func (m *ServerMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerMessage.Merge(m, src)
}
func (m *ServerMessage) XXX_Size() int {
	return xxx_messageInfo_ServerMessage.Size(m)
}
func (m *ServerMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ServerMessage proto.InternalMessageInfo

func (m *ServerMessage) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type isServerMessage_MessageType interface {
	isServerMessage_MessageType()
}

type ServerMessage_AckResponse struct {
	AckResponse *AckResponse `protobuf:"bytes,2,opt,name=ack_response,json=ackResponse,proto3,oneof"`
}

type ServerMessage_NoopRequest struct {
	NoopRequest *NoopRequest `protobuf:"bytes,3,opt,name=noop_request,json=noopRequest,proto3,oneof"`
}

type ServerMessage_ErrorResponse struct {
	ErrorResponse *ErrorResponse `protobuf:"bytes,4,opt,name=error_response,json=errorResponse,proto3,oneof"`
}

type ServerMessage_ClaimRequest struct {
	ClaimRequest *ClaimRequest `protobuf:"bytes,5,opt,name=claim_request,json=claimRequest,proto3,oneof"`
}

type ServerMessage_ConfigChangedRequest struct {
	ConfigChangedRequest *ConfigChangedRequest `protobuf:"bytes,6,opt,name=config_changed_request,json=configChangedRequest,proto3,oneof"`
}

func (*ServerMessage_AckResponse) isServerMessage_MessageType() {}

func (*ServerMessage_NoopRequest) isServerMessage_MessageType() {}

func (*ServerMessage_ErrorResponse) isServerMessage_MessageType() {}

func (*ServerMessage_ClaimRequest) isServerMessage_MessageType() {}

func (*ServerMessage_ConfigChangedRequest) isServerMessage_MessageType() {}

func (m *ServerMessage) GetMessageType() isServerMessage_MessageType {
	if m != nil {
		return m.MessageType
	}
	return nil
}

func (m *ServerMessage) GetAckResponse() *AckResponse {
	if x, ok := m.GetMessageType().(*ServerMessage_AckResponse); ok {
		return x.AckResponse
	}
	return nil
}

func (m *ServerMessage) GetNoopRequest() *NoopRequest {
	if x, ok := m.GetMessageType().(*ServerMessage_NoopRequest); ok {
		return x.NoopRequest
	}
	return nil
}

func (m *ServerMessage) GetErrorResponse() *ErrorResponse {
	if x, ok := m.GetMessageType().(*ServerMessage_ErrorResponse); ok {
		return x.ErrorResponse
	}
	return nil
}

func (m *ServerMessage) GetClaimRequest() *ClaimRequest {
	if x, ok := m.GetMessageType().(*ServerMessage_ClaimRequest); ok {
		return x.ClaimRequest
	}
	return nil
}

func (m *ServerMessage) GetConfigChangedRequest() *ConfigChangedRequest {
	if x, ok := m.GetMessageType().(*ServerMessage_ConfigChangedRequest); ok {
		return x.ConfigChangedRequest
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ServerMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ServerMessage_AckResponse)(nil),
		(*ServerMessage_NoopRequest)(nil),
		(*ServerMessage_ErrorResponse)(nil),
		(*ServerMessage_ClaimRequest)(nil),
		(*ServerMessage_ConfigChangedRequest)(nil),
	}
}

type AckResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckResponse) Reset()         { *m = AckResponse{} }
func (m *AckResponse) String() string { return proto.CompactTextString(m) }
func (*AckResponse) ProtoMessage()    {}
func (*AckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{2}
}

func (m *AckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckResponse.Unmarshal(m, b)
}
func (m *AckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckResponse.Marshal(b, m, deterministic)
}
func (m *AckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckResponse.Merge(m, src)
}
func (m *AckResponse) XXX_Size() int {
	return xxx_messageInfo_AckResponse.Size(m)
}
func (m *AckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AckResponse proto.InternalMessageInfo

type ClaimRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClaimRequest) Reset()         { *m = ClaimRequest{} }
func (m *ClaimRequest) String() string { return proto.CompactTextString(m) }
func (*ClaimRequest) ProtoMessage()    {}
func (*ClaimRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{3}
}

func (m *ClaimRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClaimRequest.Unmarshal(m, b)
}
func (m *ClaimRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClaimRequest.Marshal(b, m, deterministic)
}
func (m *ClaimRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClaimRequest.Merge(m, src)
}
func (m *ClaimRequest) XXX_Size() int {
	return xxx_messageInfo_ClaimRequest.Size(m)
}
func (m *ClaimRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClaimRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClaimRequest proto.InternalMessageInfo

func (m *ClaimRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ConfigChangedRequest struct {
	HashesByTable        map[string][]byte `protobuf:"bytes,1,rep,name=hashes_by_table,json=hashesByTable,proto3" json:"hashes_by_table,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ConfigChangedRequest) Reset()         { *m = ConfigChangedRequest{} }
func (m *ConfigChangedRequest) String() string { return proto.CompactTextString(m) }
func (*ConfigChangedRequest) ProtoMessage()    {}
func (*ConfigChangedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{4}
}

func (m *ConfigChangedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigChangedRequest.Unmarshal(m, b)
}
func (m *ConfigChangedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigChangedRequest.Marshal(b, m, deterministic)
}
func (m *ConfigChangedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigChangedRequest.Merge(m, src)
}
func (m *ConfigChangedRequest) XXX_Size() int {
	return xxx_messageInfo_ConfigChangedRequest.Size(m)
}
func (m *ConfigChangedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigChangedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigChangedRequest proto.InternalMessageInfo

func (m *ConfigChangedRequest) GetHashesByTable() map[string][]byte {
	if m != nil {
		return m.HashesByTable
	}
	return nil
}

type ErrorResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorResponse) Reset()         { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()    {}
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{5}
}

func (m *ErrorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorResponse.Unmarshal(m, b)
}
func (m *ErrorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorResponse.Marshal(b, m, deterministic)
}
func (m *ErrorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorResponse.Merge(m, src)
}
func (m *ErrorResponse) XXX_Size() int {
	return xxx_messageInfo_ErrorResponse.Size(m)
}
func (m *ErrorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorResponse proto.InternalMessageInfo

func (m *ErrorResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type NoopRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoopRequest) Reset()         { *m = NoopRequest{} }
func (m *NoopRequest) String() string { return proto.CompactTextString(m) }
func (*NoopRequest) ProtoMessage()    {}
func (*NoopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{6}
}

func (m *NoopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoopRequest.Unmarshal(m, b)
}
func (m *NoopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoopRequest.Marshal(b, m, deterministic)
}
func (m *NoopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoopRequest.Merge(m, src)
}
func (m *NoopRequest) XXX_Size() int {
	return xxx_messageInfo_NoopRequest.Size(m)
}
func (m *NoopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NoopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NoopRequest proto.InternalMessageInfo

type StartupRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartupRequest) Reset()         { *m = StartupRequest{} }
func (m *StartupRequest) String() string { return proto.CompactTextString(m) }
func (*StartupRequest) ProtoMessage()    {}
func (*StartupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{7}
}

func (m *StartupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartupRequest.Unmarshal(m, b)
}
func (m *StartupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartupRequest.Marshal(b, m, deterministic)
}
func (m *StartupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartupRequest.Merge(m, src)
}
func (m *StartupRequest) XXX_Size() int {
	return xxx_messageInfo_StartupRequest.Size(m)
}
func (m *StartupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartupRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ClientMessage)(nil), "emailproto.ClientMessage")
	proto.RegisterType((*ServerMessage)(nil), "emailproto.ServerMessage")
	proto.RegisterType((*AckResponse)(nil), "emailproto.AckResponse")
	proto.RegisterType((*ClaimRequest)(nil), "emailproto.ClaimRequest")
	proto.RegisterType((*ConfigChangedRequest)(nil), "emailproto.ConfigChangedRequest")
	proto.RegisterMapType((map[string][]byte)(nil), "emailproto.ConfigChangedRequest.HashesByTableEntry")
	proto.RegisterType((*ErrorResponse)(nil), "emailproto.ErrorResponse")
	proto.RegisterType((*NoopRequest)(nil), "emailproto.NoopRequest")
	proto.RegisterType((*StartupRequest)(nil), "emailproto.StartupRequest")
}

func init() { proto.RegisterFile("email.proto", fileDescriptor_6175298cb4ed6faa) }

var fileDescriptor_6175298cb4ed6faa = []byte{
	// 426 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x93, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0xc7, 0x49, 0xda, 0x5d, 0x89, 0xc9, 0xc7, 0xae, 0xac, 0x0a, 0xc2, 0x9e, 0xaa, 0x08, 0xa4,
	0x9e, 0x7a, 0xd8, 0xbd, 0x20, 0x84, 0x04, 0xb4, 0xaa, 0xb4, 0x17, 0x38, 0x64, 0x39, 0x20, 0x71,
	0x88, 0xdc, 0x74, 0x68, 0xa3, 0xa6, 0x76, 0xb0, 0xdd, 0x95, 0xf2, 0x0a, 0xbc, 0x0f, 0x3c, 0x1f,
	0xb2, 0xbd, 0xac, 0x1d, 0xa5, 0x12, 0xe2, 0xc6, 0xcd, 0xff, 0xf1, 0x7f, 0x7e, 0x99, 0x0f, 0x07,
	0x22, 0x3c, 0xd0, 0xba, 0x99, 0xb7, 0x82, 0x2b, 0x4e, 0xc0, 0x08, 0x73, 0xce, 0x7f, 0x85, 0x90,
	0x2c, 0x9b, 0x1a, 0x99, 0xfa, 0x88, 0x52, 0xd2, 0x2d, 0x92, 0x14, 0xc2, 0x7a, 0x93, 0x05, 0xd3,
	0x60, 0x36, 0x2e, 0xc2, 0x7a, 0x43, 0xde, 0x42, 0x4c, 0xab, 0x7d, 0x29, 0x50, 0xb6, 0x9c, 0x49,
	0xcc, 0xc2, 0x69, 0x30, 0x8b, 0xae, 0x9f, 0xcf, 0x1d, 0x64, 0xfe, 0xa1, 0xda, 0x17, 0x0f, 0xd7,
	0xb7, 0x4f, 0x8a, 0x88, 0x3a, 0xa9, 0xb3, 0x19, 0xe7, 0x6d, 0x29, 0xf0, 0xfb, 0x11, 0xa5, 0xca,
	0x46, 0xc3, 0xec, 0x4f, 0x9c, 0xb7, 0x85, 0xbd, 0xd6, 0xd9, 0xcc, 0x49, 0xb2, 0x82, 0x0b, 0xa9,
	0xa8, 0x50, 0x47, 0x07, 0x18, 0x1b, 0xc0, 0x95, 0x0f, 0xb8, 0xb3, 0x16, 0xc7, 0x48, 0x65, 0x2f,
	0x42, 0x16, 0x90, 0xa2, 0x10, 0x5c, 0xb8, 0x26, 0xce, 0x0c, 0xe5, 0x85, 0x4f, 0x59, 0x69, 0x87,
	0xd7, 0x46, 0x82, 0x7e, 0x60, 0x91, 0x42, 0x7c, 0xb0, 0x13, 0x2a, 0x55, 0xd7, 0x62, 0xfe, 0x63,
	0x04, 0xc9, 0x1d, 0x8a, 0x7b, 0x14, 0xff, 0xe3, 0xe0, 0x86, 0x1d, 0x8f, 0xff, 0xb5, 0x63, 0xf2,
	0x0e, 0x92, 0xaa, 0xa1, 0xf5, 0xe1, 0xb1, 0x04, 0x3b, 0xb4, 0xcc, 0x47, 0x2c, 0xb5, 0xc1, 0xd5,
	0x10, 0x57, 0x9e, 0x26, 0x5f, 0xe0, 0x59, 0xc5, 0xd9, 0xb7, 0x7a, 0x5b, 0x56, 0x3b, 0xca, 0xb6,
	0xb8, 0x79, 0x24, 0x9d, 0x1b, 0xd2, 0xb4, 0x47, 0x32, 0xce, 0xa5, 0x35, 0x3a, 0xe2, 0xa4, 0x3a,
	0x11, 0x1f, 0x2c, 0x23, 0x81, 0xc8, 0x1b, 0x65, 0xfe, 0x12, 0x62, 0xbf, 0x30, 0x32, 0x81, 0x33,
	0xc5, 0xf7, 0xc8, 0xcc, 0x72, 0x9e, 0x16, 0x56, 0xe4, 0x3f, 0x03, 0x98, 0x9c, 0xfa, 0x2a, 0xf9,
	0x0a, 0x17, 0x3b, 0x2a, 0x77, 0x28, 0xcb, 0x75, 0x57, 0x2a, 0xba, 0x6e, 0x30, 0x0b, 0xa6, 0xa3,
	0x59, 0x74, 0x7d, 0xf3, 0xb7, 0x82, 0xe7, 0xb7, 0x26, 0x6f, 0xd1, 0x7d, 0xd6, 0x59, 0x2b, 0xa6,
	0x44, 0x57, 0x24, 0x3b, 0x3f, 0x76, 0xf5, 0x1e, 0xc8, 0xd0, 0x44, 0x2e, 0x61, 0xb4, 0xc7, 0xee,
	0xa1, 0x3e, 0x7d, 0xd4, 0x35, 0xdf, 0xd3, 0xe6, 0x68, 0x9f, 0x4d, 0x5c, 0x58, 0xf1, 0x26, 0x7c,
	0x1d, 0xe4, 0xaf, 0x20, 0xe9, 0x6d, 0x4e, 0x5b, 0xcd, 0xe6, 0xfe, 0xb4, 0x67, 0x84, 0x9e, 0x89,
	0xf7, 0x40, 0xf2, 0x4b, 0x48, 0xfb, 0xff, 0xc9, 0xfa, 0xdc, 0xf4, 0x71, 0xf3, 0x3b, 0x00, 0x00,
	0xff, 0xff, 0x49, 0xee, 0x1e, 0x63, 0x1c, 0x04, 0x00, 0x00,
}
