// Code generated by protoc-gen-go. DO NOT EDIT.
// source: email.proto

package emailproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClientMessage struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to MessageType:
	//	*ClientMessage_AckResponse
	//	*ClientMessage_ErrorResponse
	//	*ClientMessage_NoopRequest
	//	*ClientMessage_StartupRequest
	//	*ClientMessage_GetSnapshotsRequest
	//	*ClientMessage_UpdateSnapshotRequest
	//	*ClientMessage_GetSnapshotChunksMissingRequest
	//	*ClientMessage_SetSnapshotChunkRequest
	//	*ClientMessage_GetEndpointsRequest
	//	*ClientMessage_GetAccountsRequest
	//	*ClientMessage_GetDomainsRequest
	MessageType          isClientMessage_MessageType `protobuf_oneof:"message_type"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ClientMessage) Reset()         { *m = ClientMessage{} }
func (m *ClientMessage) String() string { return proto.CompactTextString(m) }
func (*ClientMessage) ProtoMessage()    {}
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{0}
}

func (m *ClientMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientMessage.Unmarshal(m, b)
}
func (m *ClientMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientMessage.Marshal(b, m, deterministic)
}
func (m *ClientMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientMessage.Merge(m, src)
}
func (m *ClientMessage) XXX_Size() int {
	return xxx_messageInfo_ClientMessage.Size(m)
}
func (m *ClientMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ClientMessage proto.InternalMessageInfo

func (m *ClientMessage) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type isClientMessage_MessageType interface {
	isClientMessage_MessageType()
}

type ClientMessage_AckResponse struct {
	AckResponse *AckResponse `protobuf:"bytes,2,opt,name=ack_response,json=ackResponse,proto3,oneof"`
}

type ClientMessage_ErrorResponse struct {
	ErrorResponse *ErrorResponse `protobuf:"bytes,3,opt,name=error_response,json=errorResponse,proto3,oneof"`
}

type ClientMessage_NoopRequest struct {
	NoopRequest *NoopRequest `protobuf:"bytes,4,opt,name=noop_request,json=noopRequest,proto3,oneof"`
}

type ClientMessage_StartupRequest struct {
	StartupRequest *StartupRequest `protobuf:"bytes,5,opt,name=startup_request,json=startupRequest,proto3,oneof"`
}

type ClientMessage_GetSnapshotsRequest struct {
	GetSnapshotsRequest *GetSnapshotsRequest `protobuf:"bytes,6,opt,name=get_snapshots_request,json=getSnapshotsRequest,proto3,oneof"`
}

type ClientMessage_UpdateSnapshotRequest struct {
	UpdateSnapshotRequest *UpdateSnapshotRequest `protobuf:"bytes,7,opt,name=update_snapshot_request,json=updateSnapshotRequest,proto3,oneof"`
}

type ClientMessage_GetSnapshotChunksMissingRequest struct {
	GetSnapshotChunksMissingRequest *GetSnapshotChunksMissingRequest `protobuf:"bytes,8,opt,name=get_snapshot_chunks_missing_request,json=getSnapshotChunksMissingRequest,proto3,oneof"`
}

type ClientMessage_SetSnapshotChunkRequest struct {
	SetSnapshotChunkRequest *SetSnapshotChunkRequest `protobuf:"bytes,9,opt,name=set_snapshot_chunk_request,json=setSnapshotChunkRequest,proto3,oneof"`
}

type ClientMessage_GetEndpointsRequest struct {
	GetEndpointsRequest *GetEndpointsRequest `protobuf:"bytes,10,opt,name=get_endpoints_request,json=getEndpointsRequest,proto3,oneof"`
}

type ClientMessage_GetAccountsRequest struct {
	GetAccountsRequest *GetAccountsRequest `protobuf:"bytes,1001,opt,name=get_accounts_request,json=getAccountsRequest,proto3,oneof"`
}

type ClientMessage_GetDomainsRequest struct {
	GetDomainsRequest *GetDomainsRequest `protobuf:"bytes,1002,opt,name=get_domains_request,json=getDomainsRequest,proto3,oneof"`
}

func (*ClientMessage_AckResponse) isClientMessage_MessageType() {}

func (*ClientMessage_ErrorResponse) isClientMessage_MessageType() {}

func (*ClientMessage_NoopRequest) isClientMessage_MessageType() {}

func (*ClientMessage_StartupRequest) isClientMessage_MessageType() {}

func (*ClientMessage_GetSnapshotsRequest) isClientMessage_MessageType() {}

func (*ClientMessage_UpdateSnapshotRequest) isClientMessage_MessageType() {}

func (*ClientMessage_GetSnapshotChunksMissingRequest) isClientMessage_MessageType() {}

func (*ClientMessage_SetSnapshotChunkRequest) isClientMessage_MessageType() {}

func (*ClientMessage_GetEndpointsRequest) isClientMessage_MessageType() {}

func (*ClientMessage_GetAccountsRequest) isClientMessage_MessageType() {}

func (*ClientMessage_GetDomainsRequest) isClientMessage_MessageType() {}

func (m *ClientMessage) GetMessageType() isClientMessage_MessageType {
	if m != nil {
		return m.MessageType
	}
	return nil
}

func (m *ClientMessage) GetAckResponse() *AckResponse {
	if x, ok := m.GetMessageType().(*ClientMessage_AckResponse); ok {
		return x.AckResponse
	}
	return nil
}

func (m *ClientMessage) GetErrorResponse() *ErrorResponse {
	if x, ok := m.GetMessageType().(*ClientMessage_ErrorResponse); ok {
		return x.ErrorResponse
	}
	return nil
}

func (m *ClientMessage) GetNoopRequest() *NoopRequest {
	if x, ok := m.GetMessageType().(*ClientMessage_NoopRequest); ok {
		return x.NoopRequest
	}
	return nil
}

func (m *ClientMessage) GetStartupRequest() *StartupRequest {
	if x, ok := m.GetMessageType().(*ClientMessage_StartupRequest); ok {
		return x.StartupRequest
	}
	return nil
}

func (m *ClientMessage) GetGetSnapshotsRequest() *GetSnapshotsRequest {
	if x, ok := m.GetMessageType().(*ClientMessage_GetSnapshotsRequest); ok {
		return x.GetSnapshotsRequest
	}
	return nil
}

func (m *ClientMessage) GetUpdateSnapshotRequest() *UpdateSnapshotRequest {
	if x, ok := m.GetMessageType().(*ClientMessage_UpdateSnapshotRequest); ok {
		return x.UpdateSnapshotRequest
	}
	return nil
}

func (m *ClientMessage) GetGetSnapshotChunksMissingRequest() *GetSnapshotChunksMissingRequest {
	if x, ok := m.GetMessageType().(*ClientMessage_GetSnapshotChunksMissingRequest); ok {
		return x.GetSnapshotChunksMissingRequest
	}
	return nil
}

func (m *ClientMessage) GetSetSnapshotChunkRequest() *SetSnapshotChunkRequest {
	if x, ok := m.GetMessageType().(*ClientMessage_SetSnapshotChunkRequest); ok {
		return x.SetSnapshotChunkRequest
	}
	return nil
}

func (m *ClientMessage) GetGetEndpointsRequest() *GetEndpointsRequest {
	if x, ok := m.GetMessageType().(*ClientMessage_GetEndpointsRequest); ok {
		return x.GetEndpointsRequest
	}
	return nil
}

func (m *ClientMessage) GetGetAccountsRequest() *GetAccountsRequest {
	if x, ok := m.GetMessageType().(*ClientMessage_GetAccountsRequest); ok {
		return x.GetAccountsRequest
	}
	return nil
}

func (m *ClientMessage) GetGetDomainsRequest() *GetDomainsRequest {
	if x, ok := m.GetMessageType().(*ClientMessage_GetDomainsRequest); ok {
		return x.GetDomainsRequest
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ClientMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ClientMessage_AckResponse)(nil),
		(*ClientMessage_ErrorResponse)(nil),
		(*ClientMessage_NoopRequest)(nil),
		(*ClientMessage_StartupRequest)(nil),
		(*ClientMessage_GetSnapshotsRequest)(nil),
		(*ClientMessage_UpdateSnapshotRequest)(nil),
		(*ClientMessage_GetSnapshotChunksMissingRequest)(nil),
		(*ClientMessage_SetSnapshotChunkRequest)(nil),
		(*ClientMessage_GetEndpointsRequest)(nil),
		(*ClientMessage_GetAccountsRequest)(nil),
		(*ClientMessage_GetDomainsRequest)(nil),
	}
}

type ServerMessage struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to MessageType:
	//	*ServerMessage_AckResponse
	//	*ServerMessage_ErrorResponse
	//	*ServerMessage_NoopRequest
	//	*ServerMessage_ClaimRequest
	//	*ServerMessage_ConfigChangedRequest
	//	*ServerMessage_StartupResponse
	//	*ServerMessage_GetSnapshotsResponse
	//	*ServerMessage_GetSnapshotChunksMissingResponse
	//	*ServerMessage_GetEndpointsResponse
	//	*ServerMessage_GetAccountsResponse
	//	*ServerMessage_GetDomainsResponse
	MessageType          isServerMessage_MessageType `protobuf_oneof:"message_type"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ServerMessage) Reset()         { *m = ServerMessage{} }
func (m *ServerMessage) String() string { return proto.CompactTextString(m) }
func (*ServerMessage) ProtoMessage()    {}
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{1}
}

func (m *ServerMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerMessage.Unmarshal(m, b)
}
func (m *ServerMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerMessage.Marshal(b, m, deterministic)
}
func (m *ServerMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerMessage.Merge(m, src)
}
func (m *ServerMessage) XXX_Size() int {
	return xxx_messageInfo_ServerMessage.Size(m)
}
func (m *ServerMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ServerMessage proto.InternalMessageInfo

func (m *ServerMessage) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type isServerMessage_MessageType interface {
	isServerMessage_MessageType()
}

type ServerMessage_AckResponse struct {
	AckResponse *AckResponse `protobuf:"bytes,2,opt,name=ack_response,json=ackResponse,proto3,oneof"`
}

type ServerMessage_ErrorResponse struct {
	ErrorResponse *ErrorResponse `protobuf:"bytes,3,opt,name=error_response,json=errorResponse,proto3,oneof"`
}

type ServerMessage_NoopRequest struct {
	NoopRequest *NoopRequest `protobuf:"bytes,4,opt,name=noop_request,json=noopRequest,proto3,oneof"`
}

type ServerMessage_ClaimRequest struct {
	ClaimRequest *ClaimRequest `protobuf:"bytes,5,opt,name=claim_request,json=claimRequest,proto3,oneof"`
}

type ServerMessage_ConfigChangedRequest struct {
	ConfigChangedRequest *ConfigChangedRequest `protobuf:"bytes,6,opt,name=config_changed_request,json=configChangedRequest,proto3,oneof"`
}

type ServerMessage_StartupResponse struct {
	StartupResponse *StartupResponse `protobuf:"bytes,7,opt,name=startup_response,json=startupResponse,proto3,oneof"`
}

type ServerMessage_GetSnapshotsResponse struct {
	GetSnapshotsResponse *GetSnapshotsResponse `protobuf:"bytes,8,opt,name=get_snapshots_response,json=getSnapshotsResponse,proto3,oneof"`
}

type ServerMessage_GetSnapshotChunksMissingResponse struct {
	GetSnapshotChunksMissingResponse *GetSnapshotChunksMissingResponse `protobuf:"bytes,9,opt,name=get_snapshot_chunks_missing_response,json=getSnapshotChunksMissingResponse,proto3,oneof"`
}

type ServerMessage_GetEndpointsResponse struct {
	GetEndpointsResponse *GetEndpointsResponse `protobuf:"bytes,10,opt,name=get_endpoints_response,json=getEndpointsResponse,proto3,oneof"`
}

type ServerMessage_GetAccountsResponse struct {
	GetAccountsResponse *GetAccountsResponse `protobuf:"bytes,1001,opt,name=get_accounts_response,json=getAccountsResponse,proto3,oneof"`
}

type ServerMessage_GetDomainsResponse struct {
	GetDomainsResponse *GetDomainsResponse `protobuf:"bytes,1002,opt,name=get_domains_response,json=getDomainsResponse,proto3,oneof"`
}

func (*ServerMessage_AckResponse) isServerMessage_MessageType() {}

func (*ServerMessage_ErrorResponse) isServerMessage_MessageType() {}

func (*ServerMessage_NoopRequest) isServerMessage_MessageType() {}

func (*ServerMessage_ClaimRequest) isServerMessage_MessageType() {}

func (*ServerMessage_ConfigChangedRequest) isServerMessage_MessageType() {}

func (*ServerMessage_StartupResponse) isServerMessage_MessageType() {}

func (*ServerMessage_GetSnapshotsResponse) isServerMessage_MessageType() {}

func (*ServerMessage_GetSnapshotChunksMissingResponse) isServerMessage_MessageType() {}

func (*ServerMessage_GetEndpointsResponse) isServerMessage_MessageType() {}

func (*ServerMessage_GetAccountsResponse) isServerMessage_MessageType() {}

func (*ServerMessage_GetDomainsResponse) isServerMessage_MessageType() {}

func (m *ServerMessage) GetMessageType() isServerMessage_MessageType {
	if m != nil {
		return m.MessageType
	}
	return nil
}

func (m *ServerMessage) GetAckResponse() *AckResponse {
	if x, ok := m.GetMessageType().(*ServerMessage_AckResponse); ok {
		return x.AckResponse
	}
	return nil
}

func (m *ServerMessage) GetErrorResponse() *ErrorResponse {
	if x, ok := m.GetMessageType().(*ServerMessage_ErrorResponse); ok {
		return x.ErrorResponse
	}
	return nil
}

func (m *ServerMessage) GetNoopRequest() *NoopRequest {
	if x, ok := m.GetMessageType().(*ServerMessage_NoopRequest); ok {
		return x.NoopRequest
	}
	return nil
}

func (m *ServerMessage) GetClaimRequest() *ClaimRequest {
	if x, ok := m.GetMessageType().(*ServerMessage_ClaimRequest); ok {
		return x.ClaimRequest
	}
	return nil
}

func (m *ServerMessage) GetConfigChangedRequest() *ConfigChangedRequest {
	if x, ok := m.GetMessageType().(*ServerMessage_ConfigChangedRequest); ok {
		return x.ConfigChangedRequest
	}
	return nil
}

func (m *ServerMessage) GetStartupResponse() *StartupResponse {
	if x, ok := m.GetMessageType().(*ServerMessage_StartupResponse); ok {
		return x.StartupResponse
	}
	return nil
}

func (m *ServerMessage) GetGetSnapshotsResponse() *GetSnapshotsResponse {
	if x, ok := m.GetMessageType().(*ServerMessage_GetSnapshotsResponse); ok {
		return x.GetSnapshotsResponse
	}
	return nil
}

func (m *ServerMessage) GetGetSnapshotChunksMissingResponse() *GetSnapshotChunksMissingResponse {
	if x, ok := m.GetMessageType().(*ServerMessage_GetSnapshotChunksMissingResponse); ok {
		return x.GetSnapshotChunksMissingResponse
	}
	return nil
}

func (m *ServerMessage) GetGetEndpointsResponse() *GetEndpointsResponse {
	if x, ok := m.GetMessageType().(*ServerMessage_GetEndpointsResponse); ok {
		return x.GetEndpointsResponse
	}
	return nil
}

func (m *ServerMessage) GetGetAccountsResponse() *GetAccountsResponse {
	if x, ok := m.GetMessageType().(*ServerMessage_GetAccountsResponse); ok {
		return x.GetAccountsResponse
	}
	return nil
}

func (m *ServerMessage) GetGetDomainsResponse() *GetDomainsResponse {
	if x, ok := m.GetMessageType().(*ServerMessage_GetDomainsResponse); ok {
		return x.GetDomainsResponse
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ServerMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ServerMessage_AckResponse)(nil),
		(*ServerMessage_ErrorResponse)(nil),
		(*ServerMessage_NoopRequest)(nil),
		(*ServerMessage_ClaimRequest)(nil),
		(*ServerMessage_ConfigChangedRequest)(nil),
		(*ServerMessage_StartupResponse)(nil),
		(*ServerMessage_GetSnapshotsResponse)(nil),
		(*ServerMessage_GetSnapshotChunksMissingResponse)(nil),
		(*ServerMessage_GetEndpointsResponse)(nil),
		(*ServerMessage_GetAccountsResponse)(nil),
		(*ServerMessage_GetDomainsResponse)(nil),
	}
}

type Account struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DomainId             string   `protobuf:"bytes,3,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	First                string   `protobuf:"bytes,5,opt,name=first,proto3" json:"first,omitempty"`
	Last                 string   `protobuf:"bytes,6,opt,name=last,proto3" json:"last,omitempty"`
	DisplayName          string   `protobuf:"bytes,7,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Password             []byte   `protobuf:"bytes,8,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{2}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Account) GetDomainId() string {
	if m != nil {
		return m.DomainId
	}
	return ""
}

func (m *Account) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Account) GetFirst() string {
	if m != nil {
		return m.First
	}
	return ""
}

func (m *Account) GetLast() string {
	if m != nil {
		return m.Last
	}
	return ""
}

func (m *Account) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Account) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

type AckResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckResponse) Reset()         { *m = AckResponse{} }
func (m *AckResponse) String() string { return proto.CompactTextString(m) }
func (*AckResponse) ProtoMessage()    {}
func (*AckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{3}
}

func (m *AckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckResponse.Unmarshal(m, b)
}
func (m *AckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckResponse.Marshal(b, m, deterministic)
}
func (m *AckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckResponse.Merge(m, src)
}
func (m *AckResponse) XXX_Size() int {
	return xxx_messageInfo_AckResponse.Size(m)
}
func (m *AckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AckResponse proto.InternalMessageInfo

type ClaimRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClaimRequest) Reset()         { *m = ClaimRequest{} }
func (m *ClaimRequest) String() string { return proto.CompactTextString(m) }
func (*ClaimRequest) ProtoMessage()    {}
func (*ClaimRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{4}
}

func (m *ClaimRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClaimRequest.Unmarshal(m, b)
}
func (m *ClaimRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClaimRequest.Marshal(b, m, deterministic)
}
func (m *ClaimRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClaimRequest.Merge(m, src)
}
func (m *ClaimRequest) XXX_Size() int {
	return xxx_messageInfo_ClaimRequest.Size(m)
}
func (m *ClaimRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClaimRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClaimRequest proto.InternalMessageInfo

func (m *ClaimRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ConfigChangedRequest struct {
	HashesByTable        map[string][]byte `protobuf:"bytes,1,rep,name=hashes_by_table,json=hashesByTable,proto3" json:"hashes_by_table,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ConfigChangedRequest) Reset()         { *m = ConfigChangedRequest{} }
func (m *ConfigChangedRequest) String() string { return proto.CompactTextString(m) }
func (*ConfigChangedRequest) ProtoMessage()    {}
func (*ConfigChangedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{5}
}

func (m *ConfigChangedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigChangedRequest.Unmarshal(m, b)
}
func (m *ConfigChangedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigChangedRequest.Marshal(b, m, deterministic)
}
func (m *ConfigChangedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigChangedRequest.Merge(m, src)
}
func (m *ConfigChangedRequest) XXX_Size() int {
	return xxx_messageInfo_ConfigChangedRequest.Size(m)
}
func (m *ConfigChangedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigChangedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigChangedRequest proto.InternalMessageInfo

func (m *ConfigChangedRequest) GetHashesByTable() map[string][]byte {
	if m != nil {
		return m.HashesByTable
	}
	return nil
}

type Domain struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServiceInstanceId    string   `protobuf:"bytes,2,opt,name=service_instance_id,json=serviceInstanceId,proto3" json:"service_instance_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Domain) Reset()         { *m = Domain{} }
func (m *Domain) String() string { return proto.CompactTextString(m) }
func (*Domain) ProtoMessage()    {}
func (*Domain) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{6}
}

func (m *Domain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Domain.Unmarshal(m, b)
}
func (m *Domain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Domain.Marshal(b, m, deterministic)
}
func (m *Domain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Domain.Merge(m, src)
}
func (m *Domain) XXX_Size() int {
	return xxx_messageInfo_Domain.Size(m)
}
func (m *Domain) XXX_DiscardUnknown() {
	xxx_messageInfo_Domain.DiscardUnknown(m)
}

var xxx_messageInfo_Domain proto.InternalMessageInfo

func (m *Domain) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Domain) GetServiceInstanceId() string {
	if m != nil {
		return m.ServiceInstanceId
	}
	return ""
}

func (m *Domain) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Endpoint struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Protocol             string   `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Port                 uint32   `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Path                 string   `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	Enabled              bool     `protobuf:"varint,6,opt,name=Enabled,proto3" json:"Enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Endpoint) Reset()         { *m = Endpoint{} }
func (m *Endpoint) String() string { return proto.CompactTextString(m) }
func (*Endpoint) ProtoMessage()    {}
func (*Endpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{7}
}

func (m *Endpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Endpoint.Unmarshal(m, b)
}
func (m *Endpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Endpoint.Marshal(b, m, deterministic)
}
func (m *Endpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Endpoint.Merge(m, src)
}
func (m *Endpoint) XXX_Size() int {
	return xxx_messageInfo_Endpoint.Size(m)
}
func (m *Endpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Endpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Endpoint proto.InternalMessageInfo

func (m *Endpoint) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Endpoint) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *Endpoint) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Endpoint) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Endpoint) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Endpoint) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

type ErrorResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorResponse) Reset()         { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()    {}
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{8}
}

func (m *ErrorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorResponse.Unmarshal(m, b)
}
func (m *ErrorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorResponse.Marshal(b, m, deterministic)
}
func (m *ErrorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorResponse.Merge(m, src)
}
func (m *ErrorResponse) XXX_Size() int {
	return xxx_messageInfo_ErrorResponse.Size(m)
}
func (m *ErrorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorResponse proto.InternalMessageInfo

func (m *ErrorResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GetAccountsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountsRequest) Reset()         { *m = GetAccountsRequest{} }
func (m *GetAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountsRequest) ProtoMessage()    {}
func (*GetAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{9}
}

func (m *GetAccountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountsRequest.Unmarshal(m, b)
}
func (m *GetAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountsRequest.Marshal(b, m, deterministic)
}
func (m *GetAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountsRequest.Merge(m, src)
}
func (m *GetAccountsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountsRequest.Size(m)
}
func (m *GetAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountsRequest proto.InternalMessageInfo

type GetAccountsResponse struct {
	Accounts             []*Account `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetAccountsResponse) Reset()         { *m = GetAccountsResponse{} }
func (m *GetAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountsResponse) ProtoMessage()    {}
func (*GetAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{10}
}

func (m *GetAccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountsResponse.Unmarshal(m, b)
}
func (m *GetAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountsResponse.Marshal(b, m, deterministic)
}
func (m *GetAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountsResponse.Merge(m, src)
}
func (m *GetAccountsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountsResponse.Size(m)
}
func (m *GetAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountsResponse proto.InternalMessageInfo

func (m *GetAccountsResponse) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type GetDomainsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDomainsRequest) Reset()         { *m = GetDomainsRequest{} }
func (m *GetDomainsRequest) String() string { return proto.CompactTextString(m) }
func (*GetDomainsRequest) ProtoMessage()    {}
func (*GetDomainsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{11}
}

func (m *GetDomainsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDomainsRequest.Unmarshal(m, b)
}
func (m *GetDomainsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDomainsRequest.Marshal(b, m, deterministic)
}
func (m *GetDomainsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDomainsRequest.Merge(m, src)
}
func (m *GetDomainsRequest) XXX_Size() int {
	return xxx_messageInfo_GetDomainsRequest.Size(m)
}
func (m *GetDomainsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDomainsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDomainsRequest proto.InternalMessageInfo

type GetDomainsResponse struct {
	Domains              []*Domain `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetDomainsResponse) Reset()         { *m = GetDomainsResponse{} }
func (m *GetDomainsResponse) String() string { return proto.CompactTextString(m) }
func (*GetDomainsResponse) ProtoMessage()    {}
func (*GetDomainsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{12}
}

func (m *GetDomainsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDomainsResponse.Unmarshal(m, b)
}
func (m *GetDomainsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDomainsResponse.Marshal(b, m, deterministic)
}
func (m *GetDomainsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDomainsResponse.Merge(m, src)
}
func (m *GetDomainsResponse) XXX_Size() int {
	return xxx_messageInfo_GetDomainsResponse.Size(m)
}
func (m *GetDomainsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDomainsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDomainsResponse proto.InternalMessageInfo

func (m *GetDomainsResponse) GetDomains() []*Domain {
	if m != nil {
		return m.Domains
	}
	return nil
}

type GetEndpointsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEndpointsRequest) Reset()         { *m = GetEndpointsRequest{} }
func (m *GetEndpointsRequest) String() string { return proto.CompactTextString(m) }
func (*GetEndpointsRequest) ProtoMessage()    {}
func (*GetEndpointsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{13}
}

func (m *GetEndpointsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEndpointsRequest.Unmarshal(m, b)
}
func (m *GetEndpointsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEndpointsRequest.Marshal(b, m, deterministic)
}
func (m *GetEndpointsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEndpointsRequest.Merge(m, src)
}
func (m *GetEndpointsRequest) XXX_Size() int {
	return xxx_messageInfo_GetEndpointsRequest.Size(m)
}
func (m *GetEndpointsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEndpointsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEndpointsRequest proto.InternalMessageInfo

type GetEndpointsResponse struct {
	Endpoints            []*Endpoint `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetEndpointsResponse) Reset()         { *m = GetEndpointsResponse{} }
func (m *GetEndpointsResponse) String() string { return proto.CompactTextString(m) }
func (*GetEndpointsResponse) ProtoMessage()    {}
func (*GetEndpointsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{14}
}

func (m *GetEndpointsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEndpointsResponse.Unmarshal(m, b)
}
func (m *GetEndpointsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEndpointsResponse.Marshal(b, m, deterministic)
}
func (m *GetEndpointsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEndpointsResponse.Merge(m, src)
}
func (m *GetEndpointsResponse) XXX_Size() int {
	return xxx_messageInfo_GetEndpointsResponse.Size(m)
}
func (m *GetEndpointsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEndpointsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEndpointsResponse proto.InternalMessageInfo

func (m *GetEndpointsResponse) GetEndpoints() []*Endpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

type GetSnapshotChunksMissingRequest struct {
	SnapshotId           string   `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSnapshotChunksMissingRequest) Reset()         { *m = GetSnapshotChunksMissingRequest{} }
func (m *GetSnapshotChunksMissingRequest) String() string { return proto.CompactTextString(m) }
func (*GetSnapshotChunksMissingRequest) ProtoMessage()    {}
func (*GetSnapshotChunksMissingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{15}
}

func (m *GetSnapshotChunksMissingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSnapshotChunksMissingRequest.Unmarshal(m, b)
}
func (m *GetSnapshotChunksMissingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSnapshotChunksMissingRequest.Marshal(b, m, deterministic)
}
func (m *GetSnapshotChunksMissingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSnapshotChunksMissingRequest.Merge(m, src)
}
func (m *GetSnapshotChunksMissingRequest) XXX_Size() int {
	return xxx_messageInfo_GetSnapshotChunksMissingRequest.Size(m)
}
func (m *GetSnapshotChunksMissingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSnapshotChunksMissingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSnapshotChunksMissingRequest proto.InternalMessageInfo

func (m *GetSnapshotChunksMissingRequest) GetSnapshotId() string {
	if m != nil {
		return m.SnapshotId
	}
	return ""
}

type GetSnapshotChunksMissingResponse struct {
	Chunks               []uint32 `protobuf:"varint,1,rep,packed,name=chunks,proto3" json:"chunks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSnapshotChunksMissingResponse) Reset()         { *m = GetSnapshotChunksMissingResponse{} }
func (m *GetSnapshotChunksMissingResponse) String() string { return proto.CompactTextString(m) }
func (*GetSnapshotChunksMissingResponse) ProtoMessage()    {}
func (*GetSnapshotChunksMissingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{16}
}

func (m *GetSnapshotChunksMissingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSnapshotChunksMissingResponse.Unmarshal(m, b)
}
func (m *GetSnapshotChunksMissingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSnapshotChunksMissingResponse.Marshal(b, m, deterministic)
}
func (m *GetSnapshotChunksMissingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSnapshotChunksMissingResponse.Merge(m, src)
}
func (m *GetSnapshotChunksMissingResponse) XXX_Size() int {
	return xxx_messageInfo_GetSnapshotChunksMissingResponse.Size(m)
}
func (m *GetSnapshotChunksMissingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSnapshotChunksMissingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSnapshotChunksMissingResponse proto.InternalMessageInfo

func (m *GetSnapshotChunksMissingResponse) GetChunks() []uint32 {
	if m != nil {
		return m.Chunks
	}
	return nil
}

type GetSnapshotsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSnapshotsRequest) Reset()         { *m = GetSnapshotsRequest{} }
func (m *GetSnapshotsRequest) String() string { return proto.CompactTextString(m) }
func (*GetSnapshotsRequest) ProtoMessage()    {}
func (*GetSnapshotsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{17}
}

func (m *GetSnapshotsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSnapshotsRequest.Unmarshal(m, b)
}
func (m *GetSnapshotsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSnapshotsRequest.Marshal(b, m, deterministic)
}
func (m *GetSnapshotsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSnapshotsRequest.Merge(m, src)
}
func (m *GetSnapshotsRequest) XXX_Size() int {
	return xxx_messageInfo_GetSnapshotsRequest.Size(m)
}
func (m *GetSnapshotsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSnapshotsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSnapshotsRequest proto.InternalMessageInfo

type GetSnapshotsResponse struct {
	Snapshots            []*Snapshot `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetSnapshotsResponse) Reset()         { *m = GetSnapshotsResponse{} }
func (m *GetSnapshotsResponse) String() string { return proto.CompactTextString(m) }
func (*GetSnapshotsResponse) ProtoMessage()    {}
func (*GetSnapshotsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{18}
}

func (m *GetSnapshotsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSnapshotsResponse.Unmarshal(m, b)
}
func (m *GetSnapshotsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSnapshotsResponse.Marshal(b, m, deterministic)
}
func (m *GetSnapshotsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSnapshotsResponse.Merge(m, src)
}
func (m *GetSnapshotsResponse) XXX_Size() int {
	return xxx_messageInfo_GetSnapshotsResponse.Size(m)
}
func (m *GetSnapshotsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSnapshotsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSnapshotsResponse proto.InternalMessageInfo

func (m *GetSnapshotsResponse) GetSnapshots() []*Snapshot {
	if m != nil {
		return m.Snapshots
	}
	return nil
}

type NoopRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoopRequest) Reset()         { *m = NoopRequest{} }
func (m *NoopRequest) String() string { return proto.CompactTextString(m) }
func (*NoopRequest) ProtoMessage()    {}
func (*NoopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{19}
}

func (m *NoopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoopRequest.Unmarshal(m, b)
}
func (m *NoopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoopRequest.Marshal(b, m, deterministic)
}
func (m *NoopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoopRequest.Merge(m, src)
}
func (m *NoopRequest) XXX_Size() int {
	return xxx_messageInfo_NoopRequest.Size(m)
}
func (m *NoopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NoopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NoopRequest proto.InternalMessageInfo

type SetSnapshotChunkRequest struct {
	SnapshotId           string   `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	Number               uint32   `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetSnapshotChunkRequest) Reset()         { *m = SetSnapshotChunkRequest{} }
func (m *SetSnapshotChunkRequest) String() string { return proto.CompactTextString(m) }
func (*SetSnapshotChunkRequest) ProtoMessage()    {}
func (*SetSnapshotChunkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{20}
}

func (m *SetSnapshotChunkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetSnapshotChunkRequest.Unmarshal(m, b)
}
func (m *SetSnapshotChunkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetSnapshotChunkRequest.Marshal(b, m, deterministic)
}
func (m *SetSnapshotChunkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetSnapshotChunkRequest.Merge(m, src)
}
func (m *SetSnapshotChunkRequest) XXX_Size() int {
	return xxx_messageInfo_SetSnapshotChunkRequest.Size(m)
}
func (m *SetSnapshotChunkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetSnapshotChunkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetSnapshotChunkRequest proto.InternalMessageInfo

func (m *SetSnapshotChunkRequest) GetSnapshotId() string {
	if m != nil {
		return m.SnapshotId
	}
	return ""
}

func (m *SetSnapshotChunkRequest) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *SetSnapshotChunkRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Snapshot struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Engine               string   `protobuf:"bytes,3,opt,name=engine,proto3" json:"engine,omitempty"`
	Progress             float32  `protobuf:"fixed32,4,opt,name=progress,proto3" json:"progress,omitempty"`
	Size                 uint64   `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	ServiceId            string   `protobuf:"bytes,6,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Snapshot) Reset()         { *m = Snapshot{} }
func (m *Snapshot) String() string { return proto.CompactTextString(m) }
func (*Snapshot) ProtoMessage()    {}
func (*Snapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{21}
}

func (m *Snapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Snapshot.Unmarshal(m, b)
}
func (m *Snapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Snapshot.Marshal(b, m, deterministic)
}
func (m *Snapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Snapshot.Merge(m, src)
}
func (m *Snapshot) XXX_Size() int {
	return xxx_messageInfo_Snapshot.Size(m)
}
func (m *Snapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_Snapshot.DiscardUnknown(m)
}

var xxx_messageInfo_Snapshot proto.InternalMessageInfo

func (m *Snapshot) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Snapshot) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Snapshot) GetEngine() string {
	if m != nil {
		return m.Engine
	}
	return ""
}

func (m *Snapshot) GetProgress() float32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

func (m *Snapshot) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Snapshot) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

type StartupRequest struct {
	ServiceId            string   `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartupRequest) Reset()         { *m = StartupRequest{} }
func (m *StartupRequest) String() string { return proto.CompactTextString(m) }
func (*StartupRequest) ProtoMessage()    {}
func (*StartupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{22}
}

func (m *StartupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartupRequest.Unmarshal(m, b)
}
func (m *StartupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartupRequest.Marshal(b, m, deterministic)
}
func (m *StartupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartupRequest.Merge(m, src)
}
func (m *StartupRequest) XXX_Size() int {
	return xxx_messageInfo_StartupRequest.Size(m)
}
func (m *StartupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartupRequest proto.InternalMessageInfo

func (m *StartupRequest) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

type StartupResponse struct {
	ConfigHashesByTable  map[string][]byte `protobuf:"bytes,1,rep,name=config_hashes_by_table,json=configHashesByTable,proto3" json:"config_hashes_by_table,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *StartupResponse) Reset()         { *m = StartupResponse{} }
func (m *StartupResponse) String() string { return proto.CompactTextString(m) }
func (*StartupResponse) ProtoMessage()    {}
func (*StartupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{23}
}

func (m *StartupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartupResponse.Unmarshal(m, b)
}
func (m *StartupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartupResponse.Marshal(b, m, deterministic)
}
func (m *StartupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartupResponse.Merge(m, src)
}
func (m *StartupResponse) XXX_Size() int {
	return xxx_messageInfo_StartupResponse.Size(m)
}
func (m *StartupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartupResponse proto.InternalMessageInfo

func (m *StartupResponse) GetConfigHashesByTable() map[string][]byte {
	if m != nil {
		return m.ConfigHashesByTable
	}
	return nil
}

type UpdateSnapshotRequest struct {
	Snapshot             *Snapshot `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateSnapshotRequest) Reset()         { *m = UpdateSnapshotRequest{} }
func (m *UpdateSnapshotRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateSnapshotRequest) ProtoMessage()    {}
func (*UpdateSnapshotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6175298cb4ed6faa, []int{24}
}

func (m *UpdateSnapshotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSnapshotRequest.Unmarshal(m, b)
}
func (m *UpdateSnapshotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSnapshotRequest.Marshal(b, m, deterministic)
}
func (m *UpdateSnapshotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSnapshotRequest.Merge(m, src)
}
func (m *UpdateSnapshotRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateSnapshotRequest.Size(m)
}
func (m *UpdateSnapshotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSnapshotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSnapshotRequest proto.InternalMessageInfo

func (m *UpdateSnapshotRequest) GetSnapshot() *Snapshot {
	if m != nil {
		return m.Snapshot
	}
	return nil
}

func init() {
	proto.RegisterType((*ClientMessage)(nil), "emailproto.ClientMessage")
	proto.RegisterType((*ServerMessage)(nil), "emailproto.ServerMessage")
	proto.RegisterType((*Account)(nil), "emailproto.Account")
	proto.RegisterType((*AckResponse)(nil), "emailproto.AckResponse")
	proto.RegisterType((*ClaimRequest)(nil), "emailproto.ClaimRequest")
	proto.RegisterType((*ConfigChangedRequest)(nil), "emailproto.ConfigChangedRequest")
	proto.RegisterMapType((map[string][]byte)(nil), "emailproto.ConfigChangedRequest.HashesByTableEntry")
	proto.RegisterType((*Domain)(nil), "emailproto.Domain")
	proto.RegisterType((*Endpoint)(nil), "emailproto.Endpoint")
	proto.RegisterType((*ErrorResponse)(nil), "emailproto.ErrorResponse")
	proto.RegisterType((*GetAccountsRequest)(nil), "emailproto.GetAccountsRequest")
	proto.RegisterType((*GetAccountsResponse)(nil), "emailproto.GetAccountsResponse")
	proto.RegisterType((*GetDomainsRequest)(nil), "emailproto.GetDomainsRequest")
	proto.RegisterType((*GetDomainsResponse)(nil), "emailproto.GetDomainsResponse")
	proto.RegisterType((*GetEndpointsRequest)(nil), "emailproto.GetEndpointsRequest")
	proto.RegisterType((*GetEndpointsResponse)(nil), "emailproto.GetEndpointsResponse")
	proto.RegisterType((*GetSnapshotChunksMissingRequest)(nil), "emailproto.GetSnapshotChunksMissingRequest")
	proto.RegisterType((*GetSnapshotChunksMissingResponse)(nil), "emailproto.GetSnapshotChunksMissingResponse")
	proto.RegisterType((*GetSnapshotsRequest)(nil), "emailproto.GetSnapshotsRequest")
	proto.RegisterType((*GetSnapshotsResponse)(nil), "emailproto.GetSnapshotsResponse")
	proto.RegisterType((*NoopRequest)(nil), "emailproto.NoopRequest")
	proto.RegisterType((*SetSnapshotChunkRequest)(nil), "emailproto.SetSnapshotChunkRequest")
	proto.RegisterType((*Snapshot)(nil), "emailproto.Snapshot")
	proto.RegisterType((*StartupRequest)(nil), "emailproto.StartupRequest")
	proto.RegisterType((*StartupResponse)(nil), "emailproto.StartupResponse")
	proto.RegisterMapType((map[string][]byte)(nil), "emailproto.StartupResponse.ConfigHashesByTableEntry")
	proto.RegisterType((*UpdateSnapshotRequest)(nil), "emailproto.UpdateSnapshotRequest")
}

func init() { proto.RegisterFile("email.proto", fileDescriptor_6175298cb4ed6faa) }

var fileDescriptor_6175298cb4ed6faa = []byte{
	// 1189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x57, 0xdf, 0x6e, 0x1b, 0xc5,
	0x17, 0xfe, 0x39, 0x49, 0x63, 0xef, 0xb1, 0x9d, 0x34, 0x63, 0x27, 0xf1, 0x2f, 0x55, 0x89, 0xbb,
	0x2d, 0x52, 0x24, 0xaa, 0x14, 0xa5, 0x5c, 0xa0, 0x0a, 0x09, 0x9a, 0x90, 0x92, 0x20, 0xb5, 0x42,
	0x13, 0x8a, 0x90, 0x8a, 0xb4, 0x9a, 0xec, 0x4e, 0xd6, 0xab, 0xd8, 0xb3, 0xcb, 0xce, 0x3a, 0xc8,
	0x20, 0xf1, 0x04, 0xdc, 0xf2, 0x28, 0x7d, 0x03, 0x6e, 0xfa, 0x28, 0xf4, 0x29, 0xd0, 0xfc, 0xd9,
	0x99, 0xfd, 0x97, 0xa4, 0xdc, 0x72, 0x37, 0xe7, 0xcc, 0x39, 0xdf, 0x39, 0xe3, 0x33, 0xdf, 0xb7,
	0x63, 0xe8, 0xd2, 0x19, 0x89, 0xa6, 0xfb, 0x49, 0x1a, 0x67, 0x31, 0x02, 0x69, 0xc8, 0xb5, 0xfb,
	0xae, 0x0d, 0xfd, 0xa3, 0x69, 0x44, 0x59, 0xf6, 0x92, 0x72, 0x4e, 0x42, 0x8a, 0xd6, 0x60, 0x29,
	0x0a, 0x46, 0xad, 0x71, 0x6b, 0x6f, 0x05, 0x2f, 0x45, 0x01, 0xfa, 0x02, 0x7a, 0xc4, 0xbf, 0xf4,
	0x52, 0xca, 0x93, 0x98, 0x71, 0x3a, 0x5a, 0x1a, 0xb7, 0xf6, 0xba, 0x07, 0xdb, 0xfb, 0x16, 0x64,
	0xff, 0xb9, 0x7f, 0x89, 0xf5, 0xf6, 0xc9, 0xff, 0x70, 0x97, 0x58, 0x13, 0x1d, 0xc2, 0x1a, 0x4d,
	0xd3, 0x38, 0xb5, 0xf9, 0xcb, 0x32, 0xff, 0xff, 0xc5, 0xfc, 0x63, 0x11, 0x51, 0x40, 0xe8, 0xd3,
	0xa2, 0x43, 0x74, 0xc0, 0xe2, 0x38, 0xf1, 0x52, 0xfa, 0xf3, 0x9c, 0xf2, 0x6c, 0xb4, 0x52, 0xef,
	0xe0, 0x55, 0x1c, 0x27, 0x58, 0x6d, 0x8b, 0x0e, 0x98, 0x35, 0xd1, 0x31, 0xac, 0xf3, 0x8c, 0xa4,
	0xd9, 0xdc, 0x02, 0xdc, 0x91, 0x00, 0x3b, 0x45, 0x80, 0x33, 0x15, 0x62, 0x31, 0xd6, 0x78, 0xc9,
	0x83, 0x5e, 0xc3, 0x66, 0x48, 0x33, 0x8f, 0x33, 0x92, 0xf0, 0x49, 0x9c, 0x71, 0x03, 0xb6, 0x2a,
	0xc1, 0x76, 0x8b, 0x60, 0xdf, 0xd0, 0xec, 0x2c, 0x8f, 0xb3, 0x88, 0x83, 0xb0, 0xee, 0x46, 0x6f,
	0x60, 0x7b, 0x9e, 0x04, 0x24, 0xa3, 0x06, 0xd9, 0x00, 0xb7, 0x25, 0xf0, 0x83, 0x22, 0xf0, 0x6b,
	0x19, 0x9a, 0x83, 0x58, 0xe8, 0xcd, 0x79, 0xd3, 0x06, 0xfa, 0x0d, 0x1e, 0x16, 0x7b, 0xf6, 0xfc,
	0xc9, 0x9c, 0x5d, 0x72, 0x6f, 0x16, 0x71, 0x1e, 0xb1, 0xd0, 0x14, 0xea, 0xc8, 0x42, 0x9f, 0x5c,
	0x73, 0x82, 0x23, 0x99, 0xf4, 0x52, 0xe5, 0xd8, 0x92, 0xbb, 0xe1, 0xcd, 0x21, 0xe8, 0x1c, 0x76,
	0x78, 0xad, 0xb8, 0xa9, 0xe9, 0xc8, 0x9a, 0x0f, 0x4b, 0x23, 0xa8, 0x00, 0xda, 0x5a, 0xdb, 0xbc,
	0x79, 0x2b, 0x1f, 0x0a, 0x65, 0x41, 0x12, 0x47, 0xac, 0x30, 0x14, 0x68, 0x1c, 0xca, 0x71, 0x1e,
	0x57, 0x1e, 0x4a, 0xd5, 0x8d, 0xce, 0x60, 0x28, 0x60, 0x89, 0xef, 0xc7, 0xf3, 0x22, 0xea, 0xdf,
	0x6a, 0x24, 0x1f, 0x55, 0x60, 0x9f, 0xeb, 0x38, 0x8b, 0x8a, 0xc2, 0x9a, 0x17, 0x7d, 0x07, 0xa2,
	0x96, 0x17, 0xc4, 0x33, 0x12, 0x31, 0x8b, 0xf9, 0x5e, 0x61, 0xde, 0xaf, 0x60, 0x7e, 0xad, 0xc2,
	0x2c, 0xe4, 0x46, 0x58, 0x75, 0x1e, 0xae, 0x41, 0x6f, 0xa6, 0x48, 0xeb, 0x65, 0x8b, 0x84, 0xba,
	0x6f, 0xdb, 0xd0, 0x3f, 0xa3, 0xe9, 0x15, 0x4d, 0xff, 0xab, 0x5c, 0xfe, 0x12, 0xfa, 0xfe, 0x94,
	0x44, 0xb3, 0x0a, 0x93, 0x47, 0xc5, 0xf4, 0x23, 0x11, 0x60, 0xf3, 0x7b, 0x7e, 0xc1, 0x46, 0x3f,
	0xc2, 0x96, 0x1f, 0xb3, 0x8b, 0x28, 0xf4, 0xfc, 0x09, 0x61, 0x21, 0x0d, 0x2a, 0x34, 0x1e, 0x97,
	0x90, 0x64, 0xe4, 0x91, 0x0a, 0xb4, 0x88, 0x43, 0xbf, 0xc1, 0x8f, 0x4e, 0xe0, 0xae, 0x95, 0x19,
	0xfd, 0xf3, 0xa8, 0xd1, 0xde, 0x6b, 0xd4, 0x19, 0xf3, 0x03, 0xad, 0xf3, 0xb2, 0x4b, 0xf4, 0x58,
	0x55, 0x1a, 0x8d, 0xd7, 0xa9, 0xf7, 0x58, 0x96, 0x1a, 0x03, 0x3a, 0x0c, 0x1b, 0xfc, 0xe8, 0x77,
	0x78, 0x74, 0xb3, 0x1e, 0xe8, 0x3a, 0x8a, 0x9c, 0x8f, 0x3f, 0x4c, 0x10, 0x4c, 0xcd, 0x71, 0x78,
	0x4b, 0x4c, 0x7e, 0xb2, 0x22, 0x5d, 0x75, 0x45, 0x68, 0x3c, 0x59, 0x81, 0x98, 0xa5, 0x93, 0xd5,
	0xfc, 0xe8, 0x07, 0x25, 0x04, 0x05, 0xc6, 0x6a, 0x60, 0x4d, 0xd9, 0xdd, 0x6b, 0x29, 0x6b, 0x80,
	0x07, 0x61, 0xdd, 0x9d, 0x2b, 0x81, 0x25, 0xad, 0x86, 0x7d, 0xdf, 0xac, 0x04, 0x86, 0xa0, 0x06,
	0x15, 0x85, 0x35, 0x6f, 0x8d, 0xb7, 0xef, 0x5a, 0xd0, 0xd6, 0x95, 0x0b, 0x8c, 0x75, 0x24, 0x63,
	0x11, 0xac, 0x30, 0x32, 0x53, 0x4c, 0x75, 0xb0, 0x5c, 0xa3, 0x7b, 0xe0, 0xa8, 0x86, 0xbc, 0x28,
	0x90, 0x14, 0x74, 0x70, 0x47, 0x39, 0x4e, 0x03, 0x34, 0x84, 0x3b, 0xb2, 0x27, 0xc9, 0x2c, 0x07,
	0x2b, 0x43, 0x78, 0x2f, 0xa2, 0x54, 0x13, 0xc6, 0xc1, 0xca, 0x10, 0xe0, 0x53, 0xa2, 0xef, 0xbe,
	0x83, 0xe5, 0x1a, 0x3d, 0x80, 0x5e, 0x10, 0xf1, 0x64, 0x4a, 0x16, 0x9e, 0x2c, 0xdc, 0x96, 0x7b,
	0x5d, 0xed, 0x7b, 0x25, 0xea, 0xef, 0x40, 0x27, 0x21, 0x9c, 0xff, 0x12, 0xa7, 0x81, 0xbc, 0x92,
	0x3d, 0x6c, 0x6c, 0xb7, 0x0f, 0xdd, 0x82, 0x82, 0xb8, 0x8f, 0xa0, 0x57, 0xe4, 0xa3, 0xe8, 0x23,
	0x8b, 0x2f, 0x29, 0xd3, 0x27, 0x54, 0x86, 0xfb, 0xb6, 0x05, 0xc3, 0x26, 0xb2, 0xa1, 0x37, 0xb0,
	0x3e, 0x21, 0x7c, 0x42, 0xb9, 0x77, 0xbe, 0xf0, 0x32, 0x72, 0x3e, 0xa5, 0xa3, 0xd6, 0x78, 0x79,
	0xaf, 0x7b, 0xf0, 0xf4, 0x36, 0x9e, 0xee, 0x9f, 0xc8, 0xbc, 0xc3, 0xc5, 0xf7, 0x22, 0xeb, 0x98,
	0x65, 0xe9, 0x02, 0xf7, 0x27, 0x45, 0xdf, 0xce, 0x57, 0x80, 0xea, 0x41, 0xe8, 0x2e, 0x2c, 0x5f,
	0xd2, 0x85, 0xee, 0x4f, 0x2c, 0x45, 0xcf, 0x57, 0x64, 0x3a, 0x57, 0x33, 0xe8, 0x61, 0x65, 0x3c,
	0x5b, 0xfa, 0xbc, 0xe5, 0xfe, 0x04, 0xab, 0x6a, 0xb6, 0xb5, 0xb1, 0xed, 0xc3, 0x80, 0xd3, 0xf4,
	0x2a, 0xf2, 0xa9, 0x17, 0x31, 0x9e, 0x11, 0x26, 0x16, 0x81, 0x9e, 0xe2, 0x86, 0xde, 0x3a, 0xd5,
	0x3b, 0xa7, 0x76, 0xcc, 0xcb, 0x76, 0xcc, 0xee, 0x1f, 0x2d, 0xe8, 0xe4, 0x37, 0xbd, 0x56, 0x40,
	0xcc, 0x40, 0x1c, 0xde, 0x8f, 0xa7, 0x1a, 0xd5, 0xd8, 0x02, 0x4c, 0xdc, 0xab, 0x1c, 0x4c, 0xac,
	0x85, 0x2f, 0x89, 0x53, 0xa5, 0xb7, 0x7d, 0x2c, 0xd7, 0xd2, 0x47, 0xb2, 0x89, 0xbe, 0x13, 0x72,
	0x8d, 0x46, 0xd0, 0x3e, 0x66, 0xe2, 0xd7, 0x08, 0xe4, 0xad, 0xe8, 0xe0, 0xdc, 0x74, 0x3f, 0x86,
	0x7e, 0x49, 0xdb, 0xe5, 0x4d, 0x13, 0x8e, 0x7c, 0x96, 0xd2, 0x70, 0x87, 0x80, 0xea, 0x9f, 0x44,
	0xf7, 0x05, 0x0c, 0x1a, 0x58, 0x87, 0x9e, 0x40, 0x27, 0xa7, 0xac, 0x1e, 0xec, 0xa0, 0xfc, 0x2d,
	0x92, 0x7b, 0xd8, 0x04, 0xb9, 0x03, 0xd8, 0xa8, 0x7d, 0x1c, 0xdd, 0x43, 0x59, 0xb2, 0xc2, 0x32,
	0xf4, 0x18, 0xda, 0x9a, 0xb6, 0x1a, 0x1a, 0x15, 0xa1, 0x55, 0x34, 0xce, 0x43, 0xdc, 0x4d, 0xd9,
	0x60, 0xf5, 0x25, 0xe0, 0x7e, 0x0b, 0xc3, 0x26, 0x1d, 0x42, 0x07, 0xe0, 0x18, 0x15, 0xd3, 0xf0,
	0xc3, 0xd2, 0x57, 0x50, 0x6f, 0x62, 0x1b, 0xe6, 0x1e, 0xc2, 0xee, 0x2d, 0xcf, 0x2a, 0xb4, 0x0b,
	0x5d, 0x23, 0xce, 0x66, 0xdc, 0x90, 0xbb, 0x4e, 0x03, 0xf7, 0x19, 0x8c, 0x6f, 0x53, 0x62, 0xb4,
	0x05, 0xab, 0x4a, 0xd8, 0x65, 0x63, 0x7d, 0xac, 0x2d, 0x7d, 0xc4, 0xea, 0x0b, 0x54, 0x1f, 0xb1,
	0xfe, 0xb1, 0x38, 0x00, 0xc7, 0x7c, 0x82, 0x9a, 0x8e, 0x68, 0x1e, 0x9b, 0x36, 0x4c, 0xb0, 0xbf,
	0xf0, 0xf5, 0x76, 0x2f, 0x60, 0xfb, 0x9a, 0x47, 0xdd, 0xad, 0x27, 0x15, 0xa7, 0x60, 0xf3, 0xd9,
	0x39, 0x4d, 0xe5, 0xf5, 0xee, 0x63, 0x6d, 0x89, 0x4b, 0x1b, 0x90, 0x8c, 0xc8, 0xcb, 0xdd, 0xc3,
	0x72, 0xed, 0xfe, 0xd9, 0x82, 0x4e, 0x5e, 0xe5, 0x83, 0x14, 0x74, 0x0b, 0x56, 0x29, 0x0b, 0x23,
	0x96, 0x73, 0x44, 0x5b, 0x9a, 0x55, 0x61, 0x4a, 0x39, 0x97, 0x4c, 0x59, 0xc2, 0xc6, 0x16, 0x38,
	0x3c, 0xfa, 0x95, 0x4a, 0xb6, 0xac, 0x60, 0xb9, 0x46, 0xf7, 0x01, 0x0c, 0xcd, 0x03, 0x2d, 0xa3,
	0x4e, 0xce, 0xee, 0xc0, 0x7d, 0x02, 0x6b, 0xe5, 0xff, 0x15, 0x95, 0x84, 0x56, 0x35, 0xe1, 0xaf,
	0x16, 0xac, 0x57, 0x5e, 0x08, 0x28, 0x32, 0x4f, 0x96, 0x66, 0x29, 0xfc, 0xec, 0x86, 0xe7, 0x85,
	0x96, 0xc6, 0x06, 0x2d, 0x1c, 0xf8, 0xf5, 0x9d, 0x9d, 0x17, 0x30, 0xba, 0x2e, 0xe1, 0x5f, 0xe9,
	0xe2, 0x29, 0x6c, 0x36, 0xfe, 0x53, 0x41, 0x9f, 0x42, 0x27, 0x1f, 0xb1, 0x44, 0xba, 0xee, 0x4a,
	0x99, 0xa8, 0xf3, 0x55, 0xb9, 0xf3, 0xf4, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa5, 0x68, 0xd3,
	0xb9, 0xc1, 0x0e, 0x00, 0x00,
}
